"""Initial migration

Revision ID: 76a41ea50be0
Revises: 
Create Date: 2025-03-31 23:34:19.968258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76a41ea50be0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_library', sa.Column('name', sa.String(), server_default='', nullable=False))
    op.add_column('exercise_library', sa.Column('difficulty', sa.String(), server_default='beginner', nullable=False))
    op.add_column('exercise_library', sa.Column('equipment', sa.String(), server_default='none', nullable=False))
    op.add_column('exercise_library', sa.Column('steps', sa.String(), server_default='[]', nullable=False))
    op.add_column('exercise_library', sa.Column('skills', sa.String(), server_default='[]', nullable=False))
    op.add_column('exercise_library', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('exercise_library', sa.Column('duration_minutes', sa.Integer(), server_default=sa.text('(30)'), nullable=False))
    op.alter_column('exercise_library', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('exercise_library', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('exercise_library', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercise_library', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('exercise_library', 'updated_at')
    op.drop_column('exercise_library', 'difficulty_level')
    op.drop_column('exercise_library', 'title')
    op.alter_column('player_stats', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.alter_column('player_stats', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('exercise_library', sa.Column('title', sa.VARCHAR(), nullable=False))
    op.add_column('exercise_library', sa.Column('difficulty_level', sa.VARCHAR(), nullable=True))
    op.add_column('exercise_library', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.alter_column('exercise_library', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('exercise_library', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercise_library', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('exercise_library', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('exercise_library', 'duration_minutes')
    op.drop_column('exercise_library', 'image_url')
    op.drop_column('exercise_library', 'skills')
    op.drop_column('exercise_library', 'steps')
    op.drop_column('exercise_library', 'equipment')
    op.drop_column('exercise_library', 'difficulty')
    op.drop_column('exercise_library', 'name')
    # ### end Alembic commands ###
