import 'dart:async';
import 'dart:math';
import 'package:http/http.dart' as http;
import '../models/exercise.dart';
import '../services/auth_service.dart';
import '../config/api_config.dart';

class ExerciseService {
  final AuthService _authService;
  
  ExerciseService(this._authService);
  
  Future<List<Exercise>> getExercises({
    String? category,
    String? difficulty,
    String? search,
    List<String>? skills,
  }) async {
    // Simulate a network delay
    await Future.delayed(const Duration(milliseconds: 800));
    
    try {
      // In a real app, we would make a network request here
      // For now, return mock data
      List<Exercise> exercises = _getMockExercises();
      
      // Apply filters
      if (category != null) {
        exercises = exercises.where((e) => e.category == category).toList();
      }
      
      if (difficulty != null) {
        exercises = exercises.where((e) => e.difficulty == difficulty).toList();
      }
      
      if (search != null && search.isNotEmpty) {
        final searchLower = search.toLowerCase();
        exercises = exercises.where((e) =>
          e.title.toLowerCase().contains(searchLower) ||
          e.description.toLowerCase().contains(searchLower)
        ).toList();
      }
      
      if (skills != null && skills.isNotEmpty) {
        exercises = exercises.where((e) =>
          e.skills != null &&
          skills.any((skill) => e.skills!.contains(skill))
        ).toList();
      }
      
      return exercises;
    } catch (e) {
      throw Exception('Failed to load exercises: $e');
    }
  }
  
  Future<Exercise> getExercise(int exerciseId) async {
    // Simulate a network delay
    await Future.delayed(const Duration(milliseconds: 500));
    
    try {
      // In a real app, we would make a network request here
      // For now, return mock data
      final exercises = _getMockExercises();
      final exercise = exercises.firstWhere(
        (e) => e.id == exerciseId.toString(),
        orElse: () => throw Exception('Exercise not found'),
      );
      
      return exercise;
    } catch (e) {
      throw Exception('Failed to load exercise: $e');
    }
  }
  
  Future<Exercise> toggleFavorite(int exerciseId) async {
    // Simulate a network delay
    await Future.delayed(const Duration(milliseconds: 300));
    
    try {
      // In a real app, we would make a network request here
      // For now, update the mock data
      final exercises = _getMockExercises();
      final index = exercises.indexWhere((e) => e.id == exerciseId.toString());
      
      if (index == -1) {
        throw Exception('Exercise not found');
      }
      
      final updatedExercise = exercises[index].copyWith(
        isFavorite: !exercises[index].isFavorite,
      );
      
      return updatedExercise;
    } catch (e) {
      throw Exception('Failed to update favorite status: $e');
    }
  }
  
  Future<List<Exercise>> getFavorites() async {
    // Simulate a network delay
    await Future.delayed(const Duration(milliseconds: 500));
    
    try {
      // In a real app, we would make a network request here
      // For now, return mock data
      final exercises = _getMockExercises();
      return exercises.where((e) => e.isFavorite).toList();
    } catch (e) {
      throw Exception('Failed to load favorites: $e');
    }
  }
  
  List<Exercise> _getMockExercises() {
    return [
      // Dribbling Category (8 exercises)
      Exercise(
        id: 'ex1',
        title: 'Precision Dribbling Circuit',
        description: 'Improve close ball control with this cone-based dribbling exercise. Players navigate through a series of cones using various techniques to enhance their close control and agility.',
        category: 'Dribbling',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=q1wTPYLKlBM',
        imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Cones', 'Balls'],
        skills: ['Ball Control', 'Agility', 'Coordination'],
        isFavorite: true,
        createdBy: 'Coach Thomas',
        createdAt: DateTime(2023, 3, 15),
      ),
      Exercise(
        id: 'ex2',
        title: 'Speed Dribbling Challenge',
        description: 'Focus on maintaining control while dribbling at high speed. Perfect for developing the ability to dribble past defenders in game situations.',
        category: 'Dribbling',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Cones', 'Balls', 'Stopwatch'],
        skills: ['Speed', 'Ball Control', 'Agility'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex3',
        title: '1v1 Dribbling Mastery',
        description: 'Practice beating defenders in one-on-one situations. Focus on using feints, changes of pace, and technical skills to get past opponents.',
        category: 'Dribbling',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Cones', 'Balls', 'Mini Goals'],
        skills: ['Dribbling', 'Creativity', 'Decision Making'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex4',
        title: 'Dribbling Under Pressure',
        description: 'Learn to maintain control while being pressured by defenders. This exercise helps develop composure and decision-making under pressure.',
        category: 'Dribbling',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 30,
        equipment: ['Balls', 'Bibs', 'Cones'],
        skills: ['Ball Control', 'Composure', 'Decision Making'],
        isFavorite: true,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex5',
        title: 'Dribbling Through Traffic',
        description: 'Navigate through a crowded area while maintaining control of the ball. Perfect for developing spatial awareness and close control.',
        category: 'Dribbling',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Cones', 'Training Mannequins'],
        skills: ['Ball Control', 'Spatial Awareness', 'Agility'],
        isFavorite: false,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex41',
        title: 'Cone Weaving Challenge',
        description: 'Navigate through a series of cones in a zigzag pattern, focusing on close control and quick direction changes.',
        category: 'Dribbling',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Cones', 'Balls'],
        skills: ['Ball Control', 'Agility', 'Coordination'],
        isFavorite: false,
        createdBy: 'Coach Thomas',
        createdAt: DateTime(2023, 3, 15),
      ),
      Exercise(
        id: 'ex42',
        title: 'Dribble and Shoot',
        description: 'Combine dribbling with shooting practice. Players dribble through cones before taking a shot on goal.',
        category: 'Dribbling',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Cones', 'Balls', 'Goal'],
        skills: ['Dribbling', 'Shooting', 'Transition'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex43',
        title: 'Dribble Tag',
        description: 'Players dribble while trying to tag each other. Develops awareness and control under pressure.',
        category: 'Dribbling',
        difficulty: 'Beginner',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Balls', 'Bibs'],
        skills: ['Ball Control', 'Awareness', 'Agility'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),

      // Passing Category (8 exercises)
      Exercise(
        id: 'ex6',
        title: 'Passing Triangle',
        description: 'Three players form a triangle and practice quick, one-touch passing. Focus on accuracy, proper weight, and using both feet.',
        category: 'Passing',
        difficulty: 'Beginner',
        videoUrl: 'https://www.youtube.com/watch?v=LoJ5dsFz59s',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls'],
        skills: ['Passing Accuracy', 'First Touch', 'Communication'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex7',
        title: 'Long Range Passing',
        description: 'Practice accurate long-range passing with proper technique. Focus on power, accuracy, and ball flight control.',
        category: 'Passing',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Cones', 'Targets'],
        skills: ['Long Passing', 'Technique', 'Power'],
        isFavorite: true,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex8',
        title: 'Passing and Moving',
        description: 'Emphasize the importance of moving after making a pass. Players work in groups, passing and then immediately moving to a new position.',
        category: 'Passing',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Bibs'],
        skills: ['Passing', 'Movement', 'Teamwork'],
        isFavorite: false,
        createdBy: 'Coach Anna',
        createdAt: DateTime(2023, 8, 14),
      ),
      Exercise(
        id: 'ex9',
        title: 'Wall Passing',
        description: 'Practice passing against a wall to improve first touch and passing accuracy. Perfect for individual training.',
        category: 'Passing',
        difficulty: 'Beginner',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Ball', 'Wall'],
        skills: ['First Touch', 'Passing Accuracy', 'Technique'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex10',
        title: 'Passing Under Pressure',
        description: 'Practice passing while being pressured by defenders. Focus on maintaining accuracy and composure under pressure.',
        category: 'Passing',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Bibs', 'Cones'],
        skills: ['Passing', 'Composure', 'Decision Making'],
        isFavorite: true,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex44',
        title: 'Passing Square',
        description: 'Four players form a square and practice various passing techniques and patterns.',
        category: 'Passing',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Cones'],
        skills: ['Passing', 'Movement', 'Teamwork'],
        isFavorite: false,
        createdBy: 'Coach Anna',
        createdAt: DateTime(2023, 8, 14),
      ),
      Exercise(
        id: 'ex45',
        title: 'One-Touch Passing',
        description: 'Practice quick, one-touch passing in small groups. Focus on accuracy and speed.',
        category: 'Passing',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Balls'],
        skills: ['First Touch', 'Passing', 'Reaction Time'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex46',
        title: 'Passing Through Gates',
        description: 'Players pass through small gates to improve accuracy and precision.',
        category: 'Passing',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Cones'],
        skills: ['Passing Accuracy', 'Technique', 'Precision'],
        isFavorite: false,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),

      // Shooting Category (8 exercises)
      Exercise(
        id: 'ex11',
        title: 'Shooting Accuracy Challenge',
        description: 'Players take shots from various positions, aiming at targets in the goal. Focus on accuracy and technique.',
        category: 'Shooting',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=VqcyMJHdE0Y',
        imageUrl: 'https://images.unsplash.com/photo-1552667466-07770ae110d0?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Goal', 'Target markers'],
        skills: ['Finishing', 'Shooting Technique', 'Mental Focus'],
        isFavorite: true,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex12',
        title: 'Volley Shooting',
        description: 'Practice shooting volleys from various angles and heights. Focus on timing and technique.',
        category: 'Shooting',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 30,
        equipment: ['Balls', 'Goal', 'Training Mannequins'],
        skills: ['Volleying', 'Timing', 'Technique'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex13',
        title: 'First-Time Finishing',
        description: 'Practice shooting first-time from various passes. Focus on quick reactions and accurate finishing.',
        category: 'Shooting',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Goal', 'Training Mannequins'],
        skills: ['Finishing', 'Reactions', 'Technique'],
        isFavorite: true,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex14',
        title: 'Free Kick Practice',
        description: 'Master the art of free kicks with various techniques and distances.',
        category: 'Shooting',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 30,
        equipment: ['Balls', 'Goal', 'Wall Dummies'],
        skills: ['Free Kicks', 'Technique', 'Power'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex15',
        title: 'Shooting Under Pressure',
        description: 'Practice shooting while being pressured by defenders. Focus on maintaining composure and accuracy.',
        category: 'Shooting',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Goal', 'Bibs'],
        skills: ['Finishing', 'Composure', 'Decision Making'],
        isFavorite: true,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex47',
        title: 'Shooting from Crosses',
        description: 'Practice finishing from various types of crosses and deliveries.',
        category: 'Shooting',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Goal', 'Training Mannequins'],
        skills: ['Finishing', 'Timing', 'Movement'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex48',
        title: 'Shooting on the Turn',
        description: 'Practice shooting after receiving the ball and turning quickly.',
        category: 'Shooting',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Goal', 'Training Mannequins'],
        skills: ['Finishing', 'First Touch', 'Technique'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex49',
        title: 'Penalty Practice',
        description: 'Develop confidence and technique in taking penalties.',
        category: 'Shooting',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Balls', 'Goal'],
        skills: ['Finishing', 'Technique', 'Mental Focus'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),

      // Defending Category (8 exercises)
      Exercise(
        id: 'ex16',
        title: 'Defensive Positioning',
        description: 'Learn proper defensive stance, positioning, and footwork. Focus on containing attackers effectively.',
        category: 'Defending',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 30,
        equipment: ['Cones', 'Balls', 'Bibs'],
        skills: ['Tackling', 'Positioning', 'Reaction Time'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex17',
        title: '1v1 Defending',
        description: 'Practice one-on-one defending scenarios. Focus on timing tackles and maintaining proper position.',
        category: 'Defending',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Bibs', 'Cones'],
        skills: ['Tackling', 'Positioning', 'Timing'],
        isFavorite: true,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex18',
        title: 'Defensive Headers',
        description: 'Practice defensive heading techniques. Focus on timing, power, and direction control.',
        category: 'Defending',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Training Mannequins'],
        skills: ['Heading', 'Timing', 'Power'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex19',
        title: 'Defensive Communication',
        description: 'Practice defensive organization and communication in small groups.',
        category: 'Defending',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 30,
        equipment: ['Balls', 'Bibs', 'Cones'],
        skills: ['Communication', 'Organization', 'Positioning'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex20',
        title: 'Recovery Runs',
        description: 'Practice recovery runs and defensive positioning after losing possession.',
        category: 'Defending',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Bibs', 'Cones'],
        skills: ['Speed', 'Positioning', 'Recovery'],
        isFavorite: true,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex50',
        title: 'Defensive Shape',
        description: 'Practice maintaining defensive shape and organization as a unit.',
        category: 'Defending',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Bibs', 'Cones'],
        skills: ['Positioning', 'Communication', 'Organization'],
        isFavorite: false,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex51',
        title: 'Slide Tackling',
        description: 'Learn proper slide tackling technique and timing.',
        category: 'Defending',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Training Mannequins'],
        skills: ['Tackling', 'Timing', 'Technique'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex52',
        title: 'Defensive Transitions',
        description: 'Practice quickly transitioning from attack to defense.',
        category: 'Defending',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Bibs', 'Cones'],
        skills: ['Recovery', 'Positioning', 'Speed'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),

      // Physical Category (8 exercises)
      Exercise(
        id: 'ex21',
        title: 'High-Intensity Shuttle Runs',
        description: 'Improve speed, agility, and endurance with timed shuttle runs.',
        category: 'Physical',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Cones', 'Stopwatch'],
        skills: ['Speed', 'Stamina', 'Agility'],
        isFavorite: false,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex22',
        title: 'Strength Training Circuit',
        description: 'Full-body strength training circuit designed specifically for footballers.',
        category: 'Physical',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 40,
        equipment: ['Weights', 'Resistance Bands', 'Medicine Balls'],
        skills: ['Strength', 'Power', 'Endurance'],
        isFavorite: false,
        createdBy: 'Coach Jason',
        createdAt: DateTime(2023, 11, 8),
      ),
      Exercise(
        id: 'ex23',
        title: 'Agility Ladder Drills',
        description: 'Comprehensive set of agility ladder exercises to develop quick feet and coordination.',
        category: 'Physical',
        difficulty: 'Beginner',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Agility Ladder', 'Cones'],
        skills: ['Footwork', 'Agility', 'Coordination'],
        isFavorite: true,
        createdBy: 'Coach Sophie',
        createdAt: DateTime(2024, 3, 1),
      ),
      Exercise(
        id: 'ex24',
        title: 'Plyometric Training',
        description: 'Develop explosive power with plyometric exercises.',
        category: 'Physical',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 30,
        equipment: ['Boxes', 'Cones', 'Medicine Balls'],
        skills: ['Power', 'Explosiveness', 'Coordination'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex25',
        title: 'Endurance Running',
        description: 'Build stamina with structured endurance running sessions.',
        category: 'Physical',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 45,
        equipment: ['Stopwatch'],
        skills: ['Stamina', 'Endurance', 'Mental Toughness'],
        isFavorite: false,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex53',
        title: 'Interval Training',
        description: 'High-intensity interval training specifically designed for footballers.',
        category: 'Physical',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 30,
        equipment: ['Cones', 'Stopwatch'],
        skills: ['Endurance', 'Speed', 'Recovery'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex54',
        title: 'Core Circuit',
        description: 'Targeted core strengthening exercises for better stability and power.',
        category: 'Physical',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Mat', 'Medicine Ball'],
        skills: ['Core Strength', 'Stability', 'Power'],
        isFavorite: false,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex55',
        title: 'Speed Ladder Work',
        description: 'Intensive speed ladder exercises to improve footwork and coordination.',
        category: 'Physical',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Agility Ladder', 'Cones'],
        skills: ['Footwork', 'Speed', 'Coordination'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),

      // Ball Control Category (8 exercises)
      Exercise(
        id: 'ex26',
        title: 'First Touch Improvement',
        description: 'Focus on controlling the ball efficiently with various body parts.',
        category: 'Ball Control',
        difficulty: 'Beginner',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Balls'],
        skills: ['First Touch', 'Control', 'Awareness'],
        isFavorite: true,
        createdBy: 'Coach David',
        createdAt: DateTime(2023, 6, 12),
      ),
      Exercise(
        id: 'ex27',
        title: 'Juggling Challenge',
        description: 'Improve ball control and coordination with various juggling techniques.',
        category: 'Ball Control',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls'],
        skills: ['Ball Control', 'Coordination', 'Balance'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex28',
        title: 'Wall Ball Control',
        description: 'Practice controlling the ball off the wall with various techniques.',
        category: 'Ball Control',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Ball', 'Wall'],
        skills: ['Ball Control', 'First Touch', 'Technique'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex29',
        title: 'Ball Control Circuit',
        description: 'Navigate through a circuit while maintaining close control of the ball.',
        category: 'Ball Control',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Balls', 'Cones', 'Training Mannequins'],
        skills: ['Ball Control', 'Agility', 'Coordination'],
        isFavorite: true,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex30',
        title: 'Pressure Ball Control',
        description: 'Practice maintaining control while being pressured by defenders.',
        category: 'Ball Control',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Bibs'],
        skills: ['Ball Control', 'Composure', 'Decision Making'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex56',
        title: 'Ball Control with Obstacles',
        description: 'Navigate through obstacles while maintaining close control of the ball.',
        category: 'Ball Control',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Cones', 'Training Mannequins'],
        skills: ['Ball Control', 'Agility', 'Coordination'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex57',
        title: 'Advanced Juggling',
        description: 'Practice advanced juggling techniques and tricks.',
        category: 'Ball Control',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['Balls'],
        skills: ['Ball Control', 'Coordination', 'Balance'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex58',
        title: 'Ball Control Under Pressure',
        description: 'Maintain control while being pressured by defenders.',
        category: 'Ball Control',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Bibs'],
        skills: ['Ball Control', 'Composure', 'Decision Making'],
        isFavorite: false,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),

      // Pace Category (8 exercises)
      Exercise(
        id: 'ex31',
        title: 'Sprint Training',
        description: 'Develop straight-line speed with these progressive sprint exercises.',
        category: 'Pace',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Cones', 'Stopwatch'],
        skills: ['Speed', 'Acceleration', 'Explosiveness'],
        isFavorite: false,
        createdBy: 'Coach Max',
        createdAt: DateTime(2023, 7, 5),
      ),
      Exercise(
        id: 'ex32',
        title: 'Acceleration Drills',
        description: 'Focus on improving acceleration from various starting positions.',
        category: 'Pace',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Cones', 'Stopwatch'],
        skills: ['Acceleration', 'Speed', 'Power'],
        isFavorite: true,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex33',
        title: 'Speed Endurance',
        description: 'Build speed endurance with repeated high-intensity sprints.',
        category: 'Pace',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 30,
        equipment: ['Cones', 'Stopwatch'],
        skills: ['Speed', 'Endurance', 'Recovery'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex34',
        title: 'Agility Speed Circuit',
        description: 'Combine speed and agility in this challenging circuit.',
        category: 'Pace',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Cones', 'Agility Ladder', 'Stopwatch'],
        skills: ['Speed', 'Agility', 'Coordination'],
        isFavorite: true,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex35',
        title: 'Reaction Speed Training',
        description: 'Improve reaction time and initial acceleration.',
        category: 'Pace',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Cones', 'Stopwatch', 'Training Mannequins'],
        skills: ['Reaction Time', 'Acceleration', 'Speed'],
        isFavorite: false,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex59',
        title: 'Sprint Endurance',
        description: 'Build endurance for repeated sprints with proper recovery.',
        category: 'Pace',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Cones', 'Stopwatch'],
        skills: ['Speed', 'Endurance', 'Recovery'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex60',
        title: 'Acceleration Ladder',
        description: 'Practice explosive acceleration from various starting positions.',
        category: 'Pace',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Agility Ladder', 'Cones'],
        skills: ['Acceleration', 'Speed', 'Power'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex61',
        title: 'Speed with Ball',
        description: 'Practice maintaining speed while dribbling the ball.',
        category: 'Pace',
        difficulty: 'Advanced',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balls', 'Cones'],
        skills: ['Speed', 'Ball Control', 'Coordination'],
        isFavorite: false,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),

      // Body Movements Category (8 exercises)
      Exercise(
        id: 'ex36',
        title: 'Balance and Coordination',
        description: 'Improve general body control with this sequence of balance-focused exercises.',
        category: 'Body Movements',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balance board', 'Agility ladder'],
        skills: ['Balance', 'Coordination', 'Body Control'],
        isFavorite: false,
        createdBy: 'Coach Laura',
        createdAt: DateTime(2023, 8, 12),
      ),
      Exercise(
        id: 'ex37',
        title: 'Dynamic Body Feints',
        description: 'Learn various body feints and movements to deceive defenders.',
        category: 'Body Movements',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Cones', 'Balls'],
        skills: ['Deception', 'Agility', 'Creativity'],
        isFavorite: false,
        createdBy: 'Coach Luis',
        createdAt: DateTime(2024, 1, 15),
      ),
      Exercise(
        id: 'ex38',
        title: 'Flexibility Training',
        description: 'Improve flexibility and range of motion with dynamic stretches.',
        category: 'Body Movements',
        difficulty: 'Beginner',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['None'],
        skills: ['Flexibility', 'Range of Motion', 'Recovery'],
        isFavorite: true,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex39',
        title: 'Core Stability',
        description: 'Strengthen core muscles for better balance and control.',
        category: 'Body Movements',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Mat', 'Medicine Ball'],
        skills: ['Core Strength', 'Balance', 'Stability'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
      Exercise(
        id: 'ex40',
        title: 'Dynamic Warm-up',
        description: 'Comprehensive dynamic warm-up routine for optimal performance.',
        category: 'Body Movements',
        difficulty: 'Beginner',
        videoUrl: 'https://www.youtube.com/watch?v=KRSmAVS_V7c',
        imageUrl: 'https://images.unsplash.com/photo-1560272564-c83b66b1ad12?q=80&w=2049&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['None'],
        skills: ['Warm-up', 'Mobility', 'Coordination'],
        isFavorite: true,
        createdBy: 'Coach James',
        createdAt: DateTime(2023, 5, 5),
      ),
      Exercise(
        id: 'ex62',
        title: 'Dynamic Stretching',
        description: 'Comprehensive dynamic stretching routine for improved flexibility.',
        category: 'Body Movements',
        difficulty: 'Beginner',
        videoUrl: 'https://www.youtube.com/watch?v=V0X2M9WGbSw',
        imageUrl: 'https://images.unsplash.com/photo-1526232761682-d26e03ac148e?q=80&w=2029&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 15,
        equipment: ['None'],
        skills: ['Flexibility', 'Mobility', 'Recovery'],
        isFavorite: false,
        createdBy: 'Coach Emma',
        createdAt: DateTime(2023, 1, 18),
      ),
      Exercise(
        id: 'ex63',
        title: 'Balance Board Training',
        description: 'Improve balance and stability using a balance board.',
        category: 'Body Movements',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=2XgXxzfNXeE',
        imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc608c6377?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 20,
        equipment: ['Balance Board', 'Balls'],
        skills: ['Balance', 'Stability', 'Coordination'],
        isFavorite: false,
        createdBy: 'Coach Sarah',
        createdAt: DateTime(2023, 4, 10),
      ),
      Exercise(
        id: 'ex64',
        title: 'Movement Patterns',
        description: 'Practice various movement patterns to improve agility and coordination.',
        category: 'Body Movements',
        difficulty: 'Intermediate',
        videoUrl: 'https://www.youtube.com/watch?v=MpWOBQs6UQc',
        imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3',
        durationMinutes: 25,
        equipment: ['Cones', 'Agility Ladder'],
        skills: ['Agility', 'Coordination', 'Movement'],
        isFavorite: false,
        createdBy: 'Coach Michael',
        createdAt: DateTime(2023, 2, 22),
      ),
    ];
  }
} 